spring.application.name=commerce
spring.config.import=optional:file:.env[.properties]

# Configuração do banco de dados PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do JWT
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION:3600000}
security.webhook.secret=${WEBHOOK_SECRET}
